apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wasp-ingest-nordic-cloud.fullname" . }}-secret
  labels:
    {{- include "wasp-ingest-nordic-cloud.labels" . | nindent 4 }}
data:
  nordicCloudMqttKeyClient: {{ .Values.config.nordicCloudMqttKeyClient | b64enc | quote }}
  nordicCloudMqttCertClient: {{ .Values.config.nordicCloudMqttCertClient | b64enc | quote }}
  nordicCloudMqttCertCa: {{ .Values.config.nordicCloudMqttCertCa | b64enc | quote }}
  nordicCloudMqttClientId: {{ .Values.config.nordicCloudMqttClientId | b64enc | quote }}
  nordicCloudMqttTopicPrefix: {{ .Values.config.nordicCloudMqttTopicPrefix | b64enc | quote }}
