mosquitto:
  enabled: true
kafka:
  enabled: true
waspthingmock:
  enabled: false
config:
  waspIngestNordicCloudPort: 3000
  nordicCloudMqttKeyClient: none
  nordicCloudMqttCertClient: none
  nordicCloudMqttCertCa: none
  nordicCloudMqttClientId: none
  nordicCloudMqttTopicPrefix: none
  nordicCloudMqttEndpoint: null
  waspIngestName: nordic-cloud
  logLevel: info
  kafkajsLogLevel: nothing
  init:
    registerIngest: true
    thingServiceName: wasp-thing-service
    thingServicePort: 80
image:
  repository: ghcr.io/digicatapult/wasp-ingest-nordic-cloud
  pullPolicy: IfNotPresent
  tag: 'v0.0.10'
  pullSecrets: ['ghcr-digicatapult']
